// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC43yGry1A5ra8uCPBAGNAxJVqwdf70-vY',
    appId: '1:774831412316:web:88b4c23a9f32de895c8299',
    messagingSenderId: '774831412316',
    projectId: 'finworth-assignment',
    authDomain: 'finworth-assignment.firebaseapp.com',
    storageBucket: 'finworth-assignment.firebasestorage.app',
    measurementId: 'G-S19JW483YN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuggpMM_nGe129TxOz5QIrS97n-8PgzDA',
    appId: '1:774831412316:android:0fc0e92ddb0f0da95c8299',
    messagingSenderId: '774831412316',
    projectId: 'finworth-assignment',
    storageBucket: 'finworth-assignment.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDomuWiRVVwbpVAxe8biwifJt8oASzVAX8',
    appId: '1:774831412316:ios:56be56becafcb54f5c8299',
    messagingSenderId: '774831412316',
    projectId: 'finworth-assignment',
    storageBucket: 'finworth-assignment.firebasestorage.app',
    iosBundleId: 'com.example.sqfliteExample',
  );
}
